[package]
name = "ptyprocess"
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "A library for cutting a string while preserving colors."
repository = "https://github.com/zhiburt/ptyprocess"
documentation = "https://docs.rs/ptyprocess"
homepage = "https://github.com/zhiburt/ptyprocess"
license = "MIT"
readme = "README.md"
keywords = ["PTY", "TTY", "fork"]
categories = ["development-tools"]

[features]
default = ["async"]
sync = []
async = ["async-fs", "futures-lite", "pin-project"]

[dependencies]
nix = "0.21.0"
async-fs = { version="1.5.0", optional=true }
futures-lite = { version="1.12.0", optional=true }
pin-project = { version="1.0.7", optional=true }
